INSERT INTO IconDefinitions (Name, Atlas, "Index")
VALUES ('ICON_DISTRICT_LIBRARY', 'ICON_ATLAS_BUILDINGS', 4),
       ('ICON_DISTRICT_UNIVERSITY', 'ICON_ATLAS_BUILDINGS', 18),
       ('ICON_DISTRICT_MADRASA', 'ICON_ATLAS_BUILDINGS', 19),
       ('ICON_DISTRICT_RESEARCH_LAB', 'ICON_ATLAS_BUILDINGS', 37);
